spring.cache:
  type: redis
  cache-names: sample-redis-cache
  redis:
    host: localhost
    port: 6379
    time-to-live: 10000000

resilience4j:
  bulkhead:
    instances:
      backendB:
        maxConcurrentCalls: 7
        maxWaitDuration: 500
  circuitbreaker:
    instances:
      backendB:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 1000
        minimumNumberOfCalls: 160
        permittedNumberOfCallsInHalfOpenState: 80
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 70
        slowCallRateThreshold: 90
        slowCallDurationThreshold: 60000